onclite: skip uses-library check
error: mismatch in the <uses-library> tags between the build system and the manifest:
 - required libraries in build system: []
                  vs. in the manifest: []
 - optional libraries in build system: []
                  vs. in the manifest: [com.sec.android.app.multiwindow]
 - tags in the manifest (vendor/aosp/prebuilt/common/apk/AEXPapers/AEXPapers.apk):
  uses-library-not-required:'com.sec.android.app.multiwindow'
note: the following options are available:
 - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
 - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles

let's just skip it until AEX team fix this